[package]
name = "esled"
version = "0.1.0"
authors = ["Evan Vigil-McClanahan <mcclanahan@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
erlang_nif-sys = "0.6.4"
sled = "0.23.0"
